export const allParticipants = [
    { code: 'AL', name: 'Albanie', artist: 'Alis', song: 'Nân' },
    { code: 'AM', name: 'Arménie', artist: 'SIMÓN', song: 'Paloma Rumba' },
    { code: 'AU', name: 'Australie', artist: 'Delta Goodrem', song: 'Eclipse' },
    { code: 'AT', name: 'Autriche', artist: 'COSMÓ', song: 'Tanzschein' },
    { code: 'AZ', name: 'Azerbaïdjan', artist: 'JIVA', song: 'Just Go' },
    {
        code: 'BE',
        name: 'Belgique',
        artist: 'ESSYLA',
        song: 'Dancing on the Ice',
    },
    { code: 'BG', name: 'Bulgarie', artist: 'DARA', song: 'Bangaranga' },
    { code: 'HR', name: 'Croatie', artist: 'LELEK', song: 'Andromeda' },
    { code: 'CY', name: 'Chypre', artist: 'Antigoni', song: 'JALLA' },
    {
        code: 'CZ',
        name: 'Tchéquie',
        artist: 'Daniel Zizka',
        song: 'CROSSROADS',
    },
    {
        code: 'DK',
        name: 'Danemark',
        artist: 'Søren Torpegaard Lund',
        song: 'Før Vi Går Hjem',
    },
    {
        code: 'EE',
        name: 'Estonie',
        artist: 'Vanilla Ninja',
        song: 'Too Epic To Be True',
    },
    {
        code: 'FI',
        name: 'Finlande',
        artist: 'Linda Lampenius x Pete Parkkonen',
        song: 'Liekinheitin',
    },
    { code: 'FR', name: 'France', artist: 'Monroe', song: 'Regarde !' },
    { code: 'GE', name: 'Géorgie', artist: 'Bzikebi', song: 'On Replay' },
    { code: 'DE', name: 'Allemagne', artist: 'Sarah Engels', song: 'Fire' },
    { code: 'GR', name: 'Grèce', artist: 'Akylas', song: 'Ferto' },
    { code: 'IL', name: 'Israël', artist: 'Noam Bettan', song: 'Michelle' },
    {
        code: 'IT',
        name: 'Italie',
        artist: 'Sal Da Vinci',
        song: 'Per Sempre Sì',
    },
    { code: 'LV', name: 'Lettonie', artist: 'Atvara', song: 'Ēnā' },
    {
        code: 'LT',
        name: 'Lituanie',
        artist: 'Lion Ceccah',
        song: 'Sólo Quiero Más',
    },
    {
        code: 'LU',
        name: 'Luxembourg',
        artist: 'Eva Marija',
        song: 'Mother Nature',
    },
    { code: 'MT', name: 'Malte', artist: 'AIDAN', song: 'Bella' },
    { code: 'MD', name: 'Moldavie', artist: 'Satoshi', song: 'Viva, Moldova!' },
    {
        code: 'ME',
        name: 'Monténégro',
        artist: 'Tamara Živković',
        song: 'Nova Zora',
    },
    { code: 'NO', name: 'Norvège', artist: 'JONAS LOVV', song: 'YA YA YA' },
    { code: 'PL', name: 'Pologne', artist: 'ALICJA', song: 'Pray' },
    { code: 'PT', name: 'Portugal', artist: 'Bandidos do Cante', song: 'Rosa' },
    {
        code: 'RO',
        name: 'Roumanie',
        artist: 'Alexandra Căpitănescu',
        song: 'Choke Me',
    },
    { code: 'SM', name: 'Saint-Marin', artist: 'SENHIT', song: 'Superstar' },
    { code: 'RS', name: 'Serbie', artist: 'LAVINA', song: 'Kraj Mene' },
    { code: 'SE', name: 'Suède', artist: 'FELICIA', song: 'My System' },
    { code: 'CH', name: 'Suisse', artist: 'Veronica Fusaro', song: 'Alice' },
    { code: 'UA', name: 'Ukraine', artist: 'LELÉKA', song: 'Ridnym' },
    {
        code: 'GB',
        name: 'Royaume-Uni',
        artist: 'LOOK MUM NO COMPUTER',
        song: 'Eins, Zwei, Drei',
    },
];

export const finalParticipants = ['AT', 'FR', 'DE', 'IT', 'GB'];

export const semiFinal1Participants = [
    'MD',
    'SE',
    'HR',
    'GR',
    'PT',
    'GE',
    'FI',
    'ME',
    'EE',
    'IL',
    'BE',
    'LT',
    'SM',
    'PL',
    'RS',
];

export const semiFinal2Participants = [
    'BG',
    'AZ',
    'RO',
    'LU',
    'CZ',
    'AM',
    'CH',
    'CY',
    'LV',
    'DK',
    'AU',
    'UA',
    'AL',
    'MT',
    'NO',
];
