export const allParticipants = [
    { code: 'AL', name: 'Albanie', artist: 'Alis', song: 'Nân', songUrl: 'https://www.youtube.com/watch?v=b9AdRrA554o&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=4&pp=iAQB8AUB' },
    { code: 'AM', name: 'Arménie', artist: 'SIMÓN', song: 'Paloma Rumba', songUrl: 'https://www.youtube.com/watch?v=5EXoK-lgocw&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=7&pp=iAQB8AUB' },
    { code: 'AU', name: 'Australie', artist: 'Delta Goodrem', song: 'Eclipse', songUrl: 'https://www.youtube.com/watch?v=EUMCr1pnaMY&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=24&pp=iAQB8AUB' },
    { code: 'AT', name: 'Autriche', artist: 'COSMÓ', song: 'Tanzschein', songUrl: 'https://www.youtube.com/watch?v=zPGP9ZphxiY&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=16&pp=iAQB8AUB' },
    { code: 'AZ', name: 'Azerbaïdjan', artist: 'JIVA', song: 'Just Go', songUrl: 'https://www.youtube.com/watch?v=iMDBPe25JhM&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=17&pp=iAQB8AUB' },
    {
        code: 'BE',
        name: 'Belgique',
        artist: 'ESSYLA',
        song: 'Dancing on the Ice',
        songUrl: 'https://www.youtube.com/watch?v=9sfI4g6DWTU&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=27&pp=iAQB8AUB',
    },
    { code: 'BG', name: 'Bulgarie', artist: 'DARA', song: 'Bangaranga', songUrl: 'https://www.youtube.com/watch?v=J3oGYo_mekw&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=1&pp=iAQB8AUB' },
    { code: 'HR', name: 'Croatie', artist: 'LELEK', song: 'Andromeda', songUrl: 'https://www.youtube.com/watch?v=vl7Jqnw10sU&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=6&pp=iAQB8AUB' },
    { code: 'CY', name: 'Chypre', artist: 'Antigoni', song: 'JALLA', songUrl: 'https://www.youtube.com/watch?v=TzSs51BiQrE&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=28&pp=iAQB8AUB' },
    {
        code: 'CZ',
        name: 'Tchéquie',
        artist: 'Daniel Zizka',
        song: 'CROSSROADS',
        songUrl: 'https://www.youtube.com/watch?v=6ea25aRGpLo&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=5&pp=iAQB8AUB',
    },
    {
        code: 'DK',
        name: 'Danemark',
        artist: 'Søren Torpegaard Lund',
        song: 'Før Vi Går Hjem',
        songUrl: 'https://www.youtube.com/watch?v=xKzEP9dwoss&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=32&pp=iAQB8AUB',
    },
    {
        code: 'EE',
        name: 'Estonie',
        artist: 'Vanilla Ninja',
        song: 'Too Epic To Be True',
        songUrl: 'https://www.youtube.com/watch?v=lOiWuol3t3o&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=15&pp=iAQB8AUB0gcJCQQLAYcqIYzv',
    },
    {
        code: 'FI',
        name: 'Finlande',
        artist: 'Linda Lampenius x Pete Parkkonen',
        song: 'Liekinheitin',
        songUrl: 'https://www.youtube.com/watch?v=9bfwNIYb96Q&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=25&pp=iAQB8AUB',
    },
    { code: 'FR', name: 'France', artist: 'Monroe', song: 'Regarde !', songUrl: 'https://www.youtube.com/watch?v=ujoCYrvvTYQ&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=20&pp=iAQB8AUB' },
    { code: 'GE', name: 'Géorgie', artist: 'Bzikebi', song: 'On Replay', songUrl: 'https://www.youtube.com/watch?v=coh-lygCINY&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=3&pp=iAQB8AUB' },
    { code: 'DE', name: 'Allemagne', artist: 'Sarah Engels', song: 'Fire', songUrl: 'https://www.youtube.com/watch?v=AzvRc3eH_rA&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=10&pp=iAQB8AUB0gcJCQQLAYcqIYzv' },
    { code: 'GR', name: 'Grèce', artist: 'Akylas', song: 'Ferto', songUrl: 'https://www.youtube.com/watch?v=NGwNTd_DA9s&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=12&pp=iAQB8AUB' },
    { code: 'IL', name: 'Israël', artist: 'Noam Bettan', song: 'Michelle', songUrl: 'https://www.youtube.com/watch?v=xWCnWSoG8nI&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=22&pp=iAQB8AUB' },
    {
        code: 'IT',
        name: 'Italie',
        artist: 'Sal Da Vinci',
        song: 'Per Sempre Sì',
        songUrl: 'https://www.youtube.com/watch?v=V406FAGkhyQ&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=8&pp=iAQB8AUB',
    },
    { code: 'LV', name: 'Lettonie', artist: 'Atvara', song: 'Ēnā', songUrl: 'https://www.youtube.com/watch?v=6C2ivaB5D00&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=33&pp=iAQB8AUB' },
    {
        code: 'LT',
        name: 'Lituanie',
        artist: 'Lion Ceccah',
        song: 'Sólo Quiero Más',
        songUrl: 'https://www.youtube.com/watch?v=0H-PXnbhG7A&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=9&pp=iAQB8AUB',
    },
    {
        code: 'LU',
        name: 'Luxembourg',
        artist: 'Eva Marija',
        song: 'Mother Nature',
        songUrl: 'https://www.youtube.com/watch?v=DmVfJSRqgnI&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=34&pp=iAQB8AUB',
    },
    { code: 'MT', name: 'Malte', artist: 'AIDAN', song: 'Bella', songUrl: 'https://www.youtube.com/watch?v=CW6mQLBh6Js&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=13&pp=iAQB8AUB' },
    { code: 'MD', name: 'Moldavie', artist: 'Satoshi', song: 'Viva, Moldova!', songUrl: 'https://www.youtube.com/watch?v=SViojHjNSzc&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=14&pp=iAQB8AUB' },
    {
        code: 'ME',
        name: 'Monténégro',
        artist: 'Tamara Živković',
        song: 'Nova Zora',
        songUrl: 'https://www.youtube.com/watch?v=nuvy2d60HbI&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=19&pp=iAQB8AUB',
    },
    { code: 'NO', name: 'Norvège', artist: 'JONAS LOVV', song: 'YA YA YA', songUrl: 'https://www.youtube.com/watch?v=MasllzWk_bQ&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=26&pp=iAQB8AUB' },
    { code: 'PL', name: 'Pologne', artist: 'ALICJA', song: 'Pray', songUrl: 'https://www.youtube.com/watch?v=q78cnYIoF9Y&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=30&pp=iAQB8AUB' },
    { code: 'PT', name: 'Portugal', artist: 'Bandidos do Cante', song: 'Rosa', songUrl: 'https://www.youtube.com/watch?v=jyHaE6GqaaQ&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=29&pp=iAQB8AUB' },
    {
        code: 'RO',
        name: 'Roumanie',
        artist: 'Alexandra Căpitănescu',
        song: 'Choke Me',
        songUrl: 'https://www.youtube.com/watch?v=yn0YmI0dPb8&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=2&pp=iAQB8AUB',
    },
    { code: 'SM', name: 'Saint-Marin', artist: 'SENHIT', song: 'Superstar', songUrl: 'https://www.youtube.com/watch?v=wOQe-fQSFxg&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=35&pp=iAQB8AUB' },
    { code: 'RS', name: 'Serbie', artist: 'LAVINA', song: 'Kraj Mene', songUrl: 'https://www.youtube.com/watch?v=FJTLKBOOE98&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=23&pp=iAQB8AUB' },
    { code: 'SE', name: 'Suède', artist: 'FELICIA', song: 'My System', songUrl: 'https://www.youtube.com/watch?v=ibbfS8iG450&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=31&pp=iAQB8AUB' },
    { code: 'CH', name: 'Suisse', artist: 'Veronica Fusaro', song: 'Alice', songUrl: 'https://www.youtube.com/watch?v=PfpYGAzW5dM&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=11&pp=iAQB8AUB' },
    { code: 'UA', name: 'Ukraine', artist: 'LELÉKA', song: 'Ridnym', songUrl: 'https://www.youtube.com/watch?v=SoEXezpblAc&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=18&pp=iAQB8AUB' },
    {
        code: 'GB',
        name: 'Royaume-Uni',
        artist: 'LOOK MUM NO COMPUTER',
        song: 'Eins, Zwei, Drei',
        songUrl: 'https://www.youtube.com/watch?v=niMKvJ-Itq8&list=PLmWYEDTNOGUJVnzG0gqW4x1-9p7ejEy67&index=21&pp=iAQB8AUB',
    },
];

export const finalParticipants = ['AT', 'FR', 'DE', 'IT', 'GB'];

export const semiFinal1Participants = [
    'MD',
    'SE',
    'HR',
    'GR',
    'PT',
    'GE',
    'FI',
    'ME',
    'EE',
    'IL',
    'BE',
    'LT',
    'SM',
    'PL',
    'RS',
];

export const semiFinal2Participants = [
    'BG',
    'AZ',
    'RO',
    'LU',
    'CZ',
    'AM',
    'CH',
    'CY',
    'LV',
    'DK',
    'AU',
    'UA',
    'AL',
    'MT',
    'NO',
];
